### ISSUE TITLE
Cannot build SDK with Xcode 11.7

### ISSUE THREAD

**Issue by avlaev** [cleverpush/cleverpush-ios-sdk#2]
After updating to 1.2.1 I cannot build the SDK with XCode 11.7. After running "pod install" and trying to build the project I get an error:
"line 144: ARCHS[@]: unbound variable
Command PhaseScriptExecution failed with a nonzero exit code"

I think the issue is introduced with SDK version 1.1.0 where I see that there have been changes for build support for Xcode 12.

If I downgrade to 1.0.5 then the build passes with no problems. Let me know if this is a bug in the SDK or you are droppng support for Xcode 11. I would prefer to have support for Xcode 11 for some more time if possible since Xcode 12 is not completely stable just yet.

**Comment by gbhrdt** [comment]
Hi @avlaev I tried building the SDK itself and also tried building an Example project with the latest SDK version with Xcode 11.7 and had no issues.
Are you building for a simulator or for a real device?
Our intention is not to drop Xcode 11 support, we want to support 11 + 12.

**Comment by avlaev** [comment]
@gbhrdt I am able to build it for a device. The issue is for simulators. I ama testing with iPhone 11 simulator running iOS 13.7.
If I revert to sdk version 1.0.5 and re-run "pod install" then it builds and runs fine. If I update to the newest version I get the error from my original post. As I said v 1.1.0 is where is starts for fail for me. Let me know if you reproduce it.

**Comment by gbhrdt** [comment]
@avlaev  We also have no issues on simulator - did a Clean before Building:
<img width="1096" alt="Screen Shot 2020-11-20 at 14 06 52" src="https://user-images.githubusercontent.com/1145196/99803560-f9434e00-2b39-11eb-92ff-1944b85bb1b0.png">

We will investigate further.
