### ISSUE TITLE
+[CleverPush handleNotificationReceived:isActive:] App Crash

### ISSUE THREAD

**Issue by atiqmumtaz507** [cleverpush/cleverpush-ios-sdk#58]
A lot of our App User are facing App Crash and the reason is the CleverPush SDK (1.4.5) has some bug. Here is the Firebase CrashLytic Log (Txt) 

**Fatal Exception: NSUnknownKeyException**
0  CoreFoundation                 0x91c9c __exceptionPreprocess
1  libobjc.A.dylib                0x14758 objc_exception_throw
2  CoreFoundation                 0x15b4a0 -[NSException init]
3  Foundation                     0x146540 -[NSObject(NSKeyValueCoding) valueForUndefinedKey:]
4  Foundation                     0x26d00 -[NSObject(NSKeyValueCoding) valueForKey:]
5  baz                            0xc84b2c **+[CleverPush handleNotificationReceived:isActive:]**
6  baz                            0xc9e148 -[CleverPushUNUserNotificationCenter cleverPushUserNotificationCenter:willPresentNotification:withCompletionHandler:]
7  baz                            0xd28fa8 FCMSwizzleWillPresentNotificationWithHandler + 481 (FIRMessagingRemoteNotificationsProxy.m:481)
8  UIKitCore                      0x22b600 -[UIApplication _handleNonLaunchSpecificActions:forScene:withTransitionContext:completion:]
9  UIKitCore                      0x1cf0d8 -[UIScene _emitSceneSettingsUpdateResponseForCompletion:afterSceneUpdateWork:]
10 UIKitCore                      0x211244 -[UIScene scene:didUpdateWithDiff:transitionContext:completion:]
11 UIKitCore                      0x19cf18 -[UIApplicationSceneClientAgent scene:handleEvent:withCompletion:]
12 FrontBoardServices             0xbdac -[FBSScene updater:didUpdateSettings:withDiff:transitionContext:completion:]
13 FrontBoardServices             0x23544 __94-[FBSWorkspaceScenesClient _queue_updateScene:withSettings:diff:transitionContext:completion:]_block_invoke_2
14 FrontBoardServices             0x9704 -[FBSWorkspace _calloutQueue_executeCalloutFromSource:withBlock:]
15 FrontBoardServices             0xf4f0 __94-[FBSWorkspaceScenesClient _queue_updateScene:withSettings:diff:transitionContext:completion:]_block_invoke
16 libdispatch.dylib              0x64198 _dispatch_client_callout
17 libdispatch.dylib              0x6ac0 _dispatch_block_invoke_direct$VARIANT$mp
18 FrontBoardServices             0xad6c __FBSSERIALQUEUE_IS_CALLING_OUT_TO_A_BLOCK__
19 FrontBoardServices             0xa2f0 -[FBSSerialQueue _targetQueue_performNextIfPossible]
20 FrontBoardServices             0xe3e0 -[FBSSerialQueue _performNextFromRunLoopSource]
21 CoreFoundation                 0xb2210 __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__
22 CoreFoundation                 0xc2238 __CFRunLoopDoSource0
23 CoreFoundation                 0x55d8 __CFRunLoopDoSources0
24 CoreFoundation                 0xaa08 __CFRunLoopRun
25 CoreFoundation                 0x1dd7c CFRunLoopRunSpecific
26 GraphicsServices               0x19a0 GSEventRunModal
27 UIKitCore                      0x4ec05c -[UIApplication _run]
28 UIKitCore                      0x281ce0 UIApplicationMain
29 baz                            0x101f4 main + 15 (AppDelegate.swift:15)

Device
Model:iPhone 7
Orientation: Portrait
RAM free: 57.47 MB
Disk free: 78.43 GB
Operating system
<img width="451" alt="Screenshot 2021-12-13 at 10 59 30" src="https://user-images.githubusercontent.com/5501450/145791237-f49e07a3-7a8f-40ec-9f62-84d2b0caf750.png">

Version:15.1.0
Orientation: Portrait
Jailbroken:No

**Comment by gbhrdt** [comment]
Hi @atiqmumtaz507  Thanks for reporting!

I see in the logs some entries like this:

```
7 baz 0xd28fa8 FCMSwizzleWillPresentNotificationWithHandler + 481 (FIRMessagingRemoteNotificationsProxy.m:481)
```

It might indicate that the Firebase SDK is involved in these crashes, but not sure.

Can you please try to disable the Swizzling of the FCM SDK by adding `FirebaseAppDelegateProxyEnabled` of type "Boolean" value "NO" in your info.plist:

![image](https://user-images.githubusercontent.com/1145196/145792600-92bb15f0-37b8-47e2-9af2-c5620e3beddb.png)


Also, can you replicate the crash on your side in any way?

I would recommend upgrading to the latest CleverPush SDK version and see if it still happens there.

**Comment by atiqmumtaz507** [comment]
@gbhrdt I tried it on iPhone Pro Max (14.7.1) and OS 15 and 15.1 but unable to reproduce the bug. **Could you maybe add try catch on [CleverPush handleNotificationReceived:isActive:]**

maybe add some log [NSObject(NSKeyValueCoding) valueForKey:] which key is wrong etc so that we could investigate further?
